language: general
sudo: required
dist: trusty

branches:
  only:
    - master

addons:
  ssh_known_hosts: elpa.emacs-china.org

before_install:
  - echo $DEPLOY_USER@$DEPLOY_HOST
  - openssl aes-256-cbc -K $encrypted_d3ac04c9de5b_key -iv $encrypted_d3ac04c9de5b_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - chmod 600 /tmp/deploy_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add /tmp/deploy_rsa
  - ssh root@elpa.emacs-china.org "uname -a && ls"
  - sudo apt-get install aria2 -qq
  - sudo apt-get install -qq emacs24-nox

script:
  - emacs --version
  - travis_retry ./download && ls && du -sh && travis_retry ./deploy

after_success:
  - TZ=Asia/Shanghai date +"https://img.shields.io/badge/last update-%Y--%m--%d %H:%M-brightgreen.svg" | xargs -i wget {} -O last-update.svg
  - rsync -av --chmod=Fu=rw,Fg=r,Fo=r last-update.svg $DEPLOY_USER@$DEPLOY_HOST:/var/elpa/

env:
  global:
  - secure: o2GyLB03+uKRfra3kx0TNC6w+ebs6TI6tepl5TkTaIC9d3DY7bcNlGW8JlPB5f/nA0A4HnaAWqGaCY0LKjemy1qynjVTI+1hupV3rY+Vu/Beu+YTEW0XZb3jgxCD0e2jeI20kzh3ntr5tVULz2h1UtsTSwEjrOYIOncZ+6zWRdhu8XQyU27gPD6ai0oyWQzJw5mlPpnaRZ7UC0GSRMXO3Dla7e+fkdKTfzILLBAj7Gqn0Q1W+BOk3yFeFwkwYqJTmJV3g1V1aQy9urBodQ82ttOPwge1+mKhfNcp9ZS/YEBb3gEwAWtF3mp+CyCgNxPnvfhvFqyGPHrYf/0FIMZyioATJW6G5poI3/E3v7/jqQSw8AkgKz09C/GDZWroLyfGyKg7R8kcSf4vbMXQc1wdOnRI/1v6tf0kA3z2sdJfxw7OkpdDbSekrXHce16UANeg6Vl6oDsz6SO0ab1CP+uE/BWgigRGyN00MGaROspDuEyOkL80ppJ0q4VhN3p1NSHngpDo/xv9LJGXZaIk2ElUAd+g1knXyIJRhrfxItRiAcf3McURUvFiJqsSDRbmjJhp6yZnzp+mJFhRkMSmmAauirHg9fwR7T43zzl3F/s59ld0BOcllMdogQTCejo76TOPFysYBhosKDd/CoVD9mFpTmJWp2p0ReJt/8U5IXKeafk=
  - secure: PElm6lmjPT5w5trMZwXQMrscUiTFdgQdcC5JyNc5UlJqA2+zETP5DGBgMQhyHDD4Vw9vpmdzNRHCoD5Nz5bYoaLjYOSd90AD7Oe19o7rPP/pWxiCWFGKqPiu+y8zbEarQ39vIi17DdfBeTTiCyBmP36FWRsSEg0stJCsTnRE7p9imw1Vwje/eYwknb8vCSMUwGTDaUK1diRbHvoJx3szTIHJ0iUygg9ww1vVdZLqggjs/TMRd5PZKlBl/B4KvFgCtZSOb6pQLA2Th//pY5pof+NGYQs8j8W//ABiX3i0eBzzybQNRiB3dBxtX/C2gGFvm+x10062osQUuDOeXebWA68njD0RGC4GxZZNGJTzgl8L5Fo5nEzA7Lc1wlzMwtu1pW2wSxGBDn6EmKsWTkC0/1eCMBZE2uMpMPtxoAL40BHXiQrAg4DxIsFD2Xqm58ZeRTJzJnN43KVYKlkBCb/kURLLQQ9rLM/iRvkXsKEocCnidtRMWnz4uByiGEQpb/SUb5mbgPerp+PJ3PkPWjkmYvWOZQfPeJBHtkp5ZIqphb1BCRea6Ji/gaYb+LtbD39isx6IQnpis0QQInZ1e3f8SPzdIsOftB2QjihxzbmMXNpA03r3Be0TXJ7urYgGWX+HxbbG+Atrgu+FClnu0lsY6436lyP/Xaim2uam8C60a/E=
  matrix:
    # GNU ELPA and MELPA provides rsync access, so use it
    # - elpa=gnu
    # - elpa=melpa
    # - elpa=melpa-stable
    - elpa=marmalade
    - elpa=org
    # Disable since http://joseito.republika.pl/sunrise-commander/ is no longer working (2018-04-08)
    # - elpa=sunrise-commander
    - elpa=user42

notifications:
  email:
    recipients:
      - xuchunyang.me@gmail.com
    on_failure: always
